spring:
  application:
    name: Redis-demo
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db;MODE=MYSQL
#    username: sa
#    password:
  datasource:
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    url: jdbc:mysql://localhost:3306/demo-node?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: everex
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
redisson:
  address: redis://127.0.0.1:6379
  connectionPoolSize: 100
  connectionMinimumIdleSize: 5